## Deliverable 2. Create a Customer Travel Destinations Map.

In [10]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [24]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../weather_database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Itarema,BR,-2.9248,-39.9167,76.80,83,90,13.85,overcast clouds
1,1,Mataura,NZ,-46.1927,168.8643,44.47,58,28,6.24,scattered clouds
2,2,Juneau,US,58.3019,-134.4197,60.80,90,100,4.61,overcast clouds
3,3,Horki,BY,54.2861,30.9842,59.90,72,99,8.48,overcast clouds
4,4,Faanui,PF,-16.4833,-151.7500,78.03,70,7,7.23,light rain

In [27]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 45
What is the maximum temperature you would like for your trip? 90

In [28]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

user_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                  (city_data_df["Max Temp"] >= min_temp)]
user_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Itarema,BR,-2.9248,-39.9167,76.80,83,90,13.85,overcast clouds
2,2,Juneau,US,58.3019,-134.4197,60.80,90,100,4.61,overcast clouds
3,3,Horki,BY,54.2861,30.9842,59.90,72,99,8.48,overcast clouds
4,4,Faanui,PF,-16.4833,-151.7500,78.03,70,7,7.23,light rain
5,5,Ancud,CL,-41.8697,-73.8203,52.23,95,100,15.03,light rain
6,6,Atuona,PF,-9.8000,-139.0333,77.50,72,0,22.10,clear sky
7,7,Vaini,TO,-21.2000,-175.2000,80.76,89,75,17.27,broken clouds
8,8,Vanimo,PG,-2.6741,141.3028,83.75,72,36,5.08,scattered clouds
9,9,Rikitea,PF,-23.1203,-134.9692,73.35,74,100,21.18,overcast clouds
10,10,Arraial Do Cabo,BR,-22.9661,-42.0278,67.87,83,98,13.85,overcast clouds

In [30]:
# 4a. Determine if there are any empty rows


user_cities_df.isnull().sum()

City_ID                0
City                   0
Country                4
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
user_cities_df.replace('',np.nan, inplace=True)

In [33]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = user_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Itarema,BR,76.80,overcast clouds,-2.9248,-39.9167,
2,Juneau,US,60.80,overcast clouds,58.3019,-134.4197,
3,Horki,BY,59.90,overcast clouds,54.2861,30.9842,
4,Faanui,PF,78.03,light rain,-16.4833,-151.7500,
5,Ancud,CL,52.23,light rain,-41.8697,-73.8203,
6,Atuona,PF,77.50,clear sky,-9.8000,-139.0333,
7,Vaini,TO,80.76,broken clouds,-21.2000,-175.2000,
8,Vanimo,PG,83.75,scattered clouds,-2.6741,141.3028,
9,Rikitea,PF,73.35,overcast clouds,-23.1203,-134.9692,
10,Arraial Do Cabo,BR,67.87,overcast clouds,-22.9661,-42.0278,

In [35]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    params["location"] = f"{lat},{lng}"

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [37]:
# 7. Drop the rows where there is no Hotel Name.
clea_hotel_df = hotel_df.loc[hotel_df["Hotel Name"]!=""]

In [39]:
# 8a. Create the output File (CSV)

output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [42]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description} </dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]




# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [43]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))